In [4]:
import pandas as pd
import seaborn as sns

In [5]:
car = pd.read_csv("car_prediction_data.csv")

In [11]:
# cleanning 


car.head()
car.info()
car.describe()
car.shape
car.isnull().sum()
car = car.dropna()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [12]:
car.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [20]:
car = pd.get_dummies(car , columns=["Car_Name","Fuel_Type","Seller_Type","Transmission"], drop_first = True , dtype = int)

In [21]:
car.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Car_Name_Activa 3g,Car_Name_Activa 4g,Car_Name_Bajaj ct 100,Car_Name_Bajaj Avenger 150,Car_Name_Bajaj Avenger 150 street,...,Car_Name_swift,Car_Name_sx4,Car_Name_verna,Car_Name_vitara brezza,Car_Name_wagon r,Car_Name_xcent,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,3.35,5.59,27000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,2013,4.75,9.54,43000,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,1
2,2017,7.25,9.85,6900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
3,2011,2.85,4.15,5200,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,1
4,2014,4.60,6.87,42450,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,1

In [26]:
from sklearn.model_selection import train_test_split
X= car.drop(["Selling_Price"] ,axis=1)
y = car["Selling_Price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0)

In [27]:
X_train.head()

,Year,Present_Price,Kms_Driven,Owner,Car_Name_Activa 3g,Car_Name_Activa 4g,Car_Name_Bajaj ct 100,Car_Name_Bajaj Avenger 150,Car_Name_Bajaj Avenger 150 street,Car_Name_Bajaj Avenger 220,...,Car_Name_swift,Car_Name_sx4,Car_Name_verna,Car_Name_vitara brezza,Car_Name_wagon r,Car_Name_xcent,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
74,2014,8.93,83000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
239,2012,4.43,23709,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
64,2017,36.23,6000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
294,2014,6.80,33019,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
286,2016,7.90,28569,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1

In [28]:
X_test.head()

,Year,Present_Price,Kms_Driven,Owner,Car_Name_Activa 3g,Car_Name_Activa 4g,Car_Name_Bajaj ct 100,Car_Name_Bajaj Avenger 150,Car_Name_Bajaj Avenger 150 street,Car_Name_Bajaj Avenger 220,...,Car_Name_swift,Car_Name_sx4,Car_Name_verna,Car_Name_vitara brezza,Car_Name_wagon r,Car_Name_xcent,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
223,2015,9.400,61381,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,1
150,2011,0.826,6000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
226,2015,5.700,24678,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
296,2016,11.600,33988,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
52,2017,19.770,15000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [29]:

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [30]:
y_pred = model.predict(X_test)

In [31]:
y_pred

array([ 7.238292  , -1.30225966,  4.61811523,  8.99130965, 17.44844873,
        5.5002077 ,  3.25884445,  1.03562422,  4.08163007,  5.01265416,
        2.81833375,  0.22383498,  5.85836852,  7.10186578,  8.1843707 ,
       18.93671622,  6.40360071,  3.29863931,  1.74952109,  9.18678985,
        4.55622839,  6.09953124,  5.82139312, 11.55438117, -1.19813297,
        1.89552037,  4.58894784,  1.24831971,  0.24605636,  3.869251  ,
        3.22150668,  6.71182893,  6.76397314,  7.38384202,  3.11285149,
        3.599321  ,  5.73103252, 13.08731291, -0.26839222,  9.04687366,
       16.2491268 , 22.59262165,  4.70964068,  5.48844138,  5.6769546 ,
       12.00517044,  3.88296332,  8.17518081,  5.56282212, 13.5625511 ,
        7.72291969,  3.43754304,  5.51297614, 23.17519683,  3.55715382,
        1.13133876, -0.06431392,  2.56234528,  3.62229057,  9.019928  ,
        5.59102045])

In [32]:
from sklearn.metrics import r2_score
r2  = r2_score(y_test , y_pred)

In [33]:
r2

0.7076077995910313

In [34]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

MAE: 1.5932934196220465

In [35]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

MSE: 7.390890797201724